//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAG.Abacus.CalendarConnector.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACAG.Abacus.CalendarConnector.Language.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abacus.
        /// </summary>
        public static string ABACUS_SETTING_NAME {
            get {
                return ResourceManager.GetString("ABACUS_SETTING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection state.
        /// </summary>
        public static string ABACUS_SETTING_POPUP_LABEL_CONNECTION_STATE {
            get {
                return ResourceManager.GetString("ABACUS_SETTING_POPUP_LABEL_CONNECTION_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ABACUS_SETTING_POPUP_LABEL_NAME {
            get {
                return ResourceManager.GetString("ABACUS_SETTING_POPUP_LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ABACUS_SETTING_POPUP_LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("ABACUS_SETTING_POPUP_LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ABACUS_SETTING_POPUP_LABEL_PORT {
            get {
                return ResourceManager.GetString("ABACUS_SETTING_POPUP_LABEL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string ABACUS_SETTING_POPUP_LABEL_URL {
            get {
                return ResourceManager.GetString("ABACUS_SETTING_POPUP_LABEL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use SSL.
        /// </summary>
        public static string ABACUS_SETTING_POPUP_LABEL_USE_SSL {
            get {
                return ResourceManager.GetString("ABACUS_SETTING_POPUP_LABEL_USE_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ABACUS_SETTING_POPUP_LABEL_USER {
            get {
                return ResourceManager.GetString("ABACUS_SETTING_POPUP_LABEL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abacus setting.
        /// </summary>
        public static string ABACUS_SETTING_POPUP_TITLE {
            get {
                return ResourceManager.GetString("ABACUS_SETTING_POPUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string ABOUT_US {
            get {
                return ResourceManager.GetString("ABOUT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020 © Copyright by ALL CONSULTING AG.
        /// </summary>
        public static string APP_FOOTER_TITLE {
            get {
                return ResourceManager.GetString("APP_FOOTER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abacus Calendar Connector.
        /// </summary>
        public static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this servicecode?.
        /// </summary>
        public static string ARE_YOU_SURE_WANT_TO_DELETE_THIS_PAYTYPE_SETTING {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE_WANT_TO_DELETE_THIS_PAYTYPE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string AWAY {
            get {
                return ResourceManager.GetString("AWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client name.
        /// </summary>
        public static string AZURE_CLIENT {
            get {
                return ResourceManager.GetString("AZURE_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client secret.
        /// </summary>
        public static string AZURE_CLIENT_SECRET {
            get {
                return ResourceManager.GetString("AZURE_CLIENT_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure tenant name.
        /// </summary>
        public static string AZURE_TENANT {
            get {
                return ResourceManager.GetString("AZURE_TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicecode.
        /// </summary>
        public static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string COMMENT {
            get {
                return ResourceManager.GetString("COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string CONFIRM_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found!.
        /// </summary>
        public static string DATA_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("DATA_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string DISPLAY_NAME {
            get {
                return ResourceManager.GetString("DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EMAIL_ADDERESS {
            get {
                return ResourceManager.GetString("EMAIL_ADDERESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        public static string ENTER_YOUR_EMAIL {
            get {
                return ResourceManager.GetString("ENTER_YOUR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string EXCHANGE_SETTING {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client name.
        /// </summary>
        public static string EXCHANGE_SETTING_AZURE_CLIENT {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_AZURE_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client secret.
        /// </summary>
        public static string EXCHANGE_SETTING_AZURE_CLIENT_SECRET {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_AZURE_CLIENT_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure tenant name.
        /// </summary>
        public static string EXCHANGE_SETTING_AZURE_TENANT {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_AZURE_TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EXCHANGE_SETTING_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string EXCHANGE_SETTING_BUTTON_CREATE {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string EXCHANGE_SETTING_BUTTON_DELETE {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EXCHANGE_SETTING_BUTTON_POPUP_CANCEL {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_BUTTON_POPUP_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EXCHANGE_SETTING_BUTTON_SAVE {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string EXCHANGE_SETTING_BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EXCHANGE_SETTING_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EXCHANGE_SETTING_EMAIL_ADDERESS {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_EMAIL_ADDERESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string EXCHANGE_SETTING_EXCHANGE_URL {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_EXCHANGE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string EXCHANGE_SETTING_EXCHANGE_VERSION {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_EXCHANGE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection state.
        /// </summary>
        public static string EXCHANGE_SETTING_HEALTH_STATUS {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_HEALTH_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login type.
        /// </summary>
        public static string EXCHANGE_SETTING_LOGIN_TYPE {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_LOGIN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EXCHANGE_SETTING_NAME {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a login type.
        /// </summary>
        public static string EXCHANGE_SETTING_SELECT_EXCHANGE_LOGIN_TYPE {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_SELECT_EXCHANGE_LOGIN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a version.
        /// </summary>
        public static string EXCHANGE_SETTING_SELECT_EXCHANGE_VERSION {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_SELECT_EXCHANGE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string EXCHANGE_SETTING_SELECTED {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string EXCHANGE_SETTING_SERVICE_USER {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_SERVICE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EXCHANGE_SETTING_SERVICE_USER_PASSWORD {
            get {
                return ResourceManager.GetString("EXCHANGE_SETTING_SERVICE_USER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string EXCHANGE_URL {
            get {
                return ResourceManager.GetString("EXCHANGE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string EXCHANGE_VERSION {
            get {
                return ResourceManager.GetString("EXCHANGE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The servicecode couldn&apos;t be addedd.
        /// </summary>
        public static string FAIL_TO_ADD_PAYTYPE {
            get {
                return ResourceManager.GetString("FAIL_TO_ADD_PAYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The servicecode couldn&apos;t be deleted.
        /// </summary>
        public static string FAIL_TO_DELETE_PAYTYPE {
            get {
                return ResourceManager.GetString("FAIL_TO_DELETE_PAYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The servicecode couldn&apos;t be updated.
        /// </summary>
        public static string FAIL_TO_UPDATE_PAYTYPE {
            get {
                return ResourceManager.GetString("FAIL_TO_UPDATE_PAYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string FORGOT_PASSWORD_TITLE {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string GESENDET {
            get {
                return ResourceManager.GetString("GESENDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicecode.
        /// </summary>
        public static string GRID_PAYTYPECODE {
            get {
                return ResourceManager.GetString("GRID_PAYTYPECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection state.
        /// </summary>
        public static string HEALTH_STATUS {
            get {
                return ResourceManager.GetString("HEALTH_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id does not match!.
        /// </summary>
        public static string ID_DOES_NOT_MATCH {
            get {
                return ResourceManager.GetString("ID_DOES_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no need to select a tenant with the role administrator.
        /// </summary>
        public static string IF_THE_USER_IS_AN_ADMINISTRATOR_THE_TENANT_MUST_BE_EMPTY {
            get {
                return ResourceManager.GetString("IF_THE_USER_IS_AN_ADMINISTRATOR_THE_TENANT_MUST_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string INFOMATION {
            get {
                return ResourceManager.GetString("INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string IS_APPOINTMENT_AWAY_STATE {
            get {
                return ResourceManager.GetString("IS_APPOINTMENT_AWAY_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string IS_APPOINTMENT_PRIVATE {
            get {
                return ResourceManager.GetString("IS_APPOINTMENT_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last test state.
        /// </summary>
        public static string LAST_TEST_STATE {
            get {
                return ResourceManager.GetString("LAST_TEST_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LOG_IN {
            get {
                return ResourceManager.GetString("LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login type.
        /// </summary>
        public static string LOGIN_TYPE {
            get {
                return ResourceManager.GetString("LOGIN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abacus.
        /// </summary>
        public static string LOGO_TITLE {
            get {
                return ResourceManager.GetString("LOGO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string MANAGE {
            get {
                return ResourceManager.GetString("MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string MANAGE_YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("MANAGE_YOUR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text should not contain more than 250 characters!.
        /// </summary>
        public static string MAX_LENGTH_OF_DISPLAY_NAME_IS_250 {
            get {
                return ResourceManager.GetString("MAX_LENGTH_OF_DISPLAY_NAME_IS_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string MENU_LOG {
            get {
                return ResourceManager.GetString("MENU_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MENU_LOG_FIELD_ERROR {
            get {
                return ResourceManager.GetString("MENU_LOG_FIELD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Data.
        /// </summary>
        public static string MENU_LOG_FIELD_LOG_DATA {
            get {
                return ResourceManager.GetString("MENU_LOG_FIELD_LOG_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string MENU_LOG_FIELD_STATUS {
            get {
                return ResourceManager.GetString("MENU_LOG_FIELD_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string MENU_LOG_FIELD_TIMESTAMP {
            get {
                return ResourceManager.GetString("MENU_LOG_FIELD_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string MENU_OVERVIEW {
            get {
                return ResourceManager.GetString("MENU_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicecode.
        /// </summary>
        public static string MENU_PAYTYPE {
            get {
                return ResourceManager.GetString("MENU_PAYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string MENU_TENANT {
            get {
                return ResourceManager.GetString("MENU_TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MENU_TENANT_DESCRIPTION {
            get {
                return ResourceManager.GetString("MENU_TENANT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MENU_USER {
            get {
                return ResourceManager.GetString("MENU_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length of display name is 3.
        /// </summary>
        public static string MIN_LENGTH_OF_DISPLAY_NAME_IS_1 {
            get {
                return ResourceManager.GetString("MIN_LENGTH_OF_DISPLAY_NAME_IS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during saving data!.
        /// </summary>
        public static string MSG_AN_ERROR_HAS_OCCURRED_DURRING_DATA_SAVING {
            get {
                return ResourceManager.GetString("MSG_AN_ERROR_HAS_OCCURRED_DURRING_DATA_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this exchange setting?.
        /// </summary>
        public static string MSG_ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_EXCHANGE_SETTING {
            get {
                return ResourceManager.GetString("MSG_ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_EXCHANGE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user?.
        /// </summary>
        public static string MSG_ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_USER {
            get {
                return ResourceManager.GetString("MSG_ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client name is required!.
        /// </summary>
        public static string MSG_AZURE_CLIENT_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_AZURE_CLIENT_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client secret is required!.
        /// </summary>
        public static string MSG_AZURE_CLIENT_SECRET_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_AZURE_CLIENT_SECRET_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure tenant name is required!.
        /// </summary>
        public static string MSG_AZURE_TENANT_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_AZURE_TENANT_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered username or password is not correct!.
        /// </summary>
        public static string MSG_CAN_NOT_IDENTITY_USER {
            get {
                return ResourceManager.GetString("MSG_CAN_NOT_IDENTITY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to delete data!.
        /// </summary>
        public static string MSG_CANT_DELETE_ROLE_WITH_EQUAL_OR_LOWER_ROLE {
            get {
                return ResourceManager.GetString("MSG_CANT_DELETE_ROLE_WITH_EQUAL_OR_LOWER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant delete user with role SysAdmin.
        /// </summary>
        public static string MSG_CANT_DELETE_SYSADMIN {
            get {
                return ResourceManager.GetString("MSG_CANT_DELETE_SYSADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant delete yourself.
        /// </summary>
        public static string MSG_CANT_DELETE_YOURSELF {
            get {
                return ResourceManager.GetString("MSG_CANT_DELETE_YOURSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password change failed!.
        /// </summary>
        public static string MSG_CHANGE_PASSWORD_FAILED {
            get {
                return ResourceManager.GetString("MSG_CHANGE_PASSWORD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here..
        /// </summary>
        public static string MSG_CLICKING_HERE {
            get {
                return ResourceManager.GetString("MSG_CLICKING_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The servicecode must be between 1 and 99999.
        /// </summary>
        public static string MSG_CODE_NUMBER_RANGE_IS_FROM_1_TO_99999 {
            get {
                return ResourceManager.GetString("MSG_CODE_NUMBER_RANGE_IS_FROM_1_TO_99999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The servicecode already exists!.
        /// </summary>
        public static string MSG_CODE_USED_FOR_ANOTHER_PAYTYPE {
            get {
                return ResourceManager.GetString("MSG_CODE_USED_FOR_ANOTHER_PAYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency failure!.
        /// </summary>
        public static string MSG_CONCURRENCY_FAILURE {
            get {
                return ResourceManager.GetString("MSG_CONCURRENCY_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this servicecode?.
        /// </summary>
        public static string MSG_CONFIRM_DELETE_RECORD {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default error.
        /// </summary>
        public static string MSG_DEFAULT_ERROR {
            get {
                return ResourceManager.GetString("MSG_DEFAULT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email exists already!.
        /// </summary>
        public static string MSG_DUPLICATE_EMAIL {
            get {
                return ResourceManager.GetString("MSG_DUPLICATE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered role name exists already!.
        /// </summary>
        public static string MSG_DUPLICATE_ROLE_NAME {
            get {
                return ResourceManager.GetString("MSG_DUPLICATE_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered user name exists already!.
        /// </summary>
        public static string MSG_DUPLICATE_USER_NAME {
            get {
                return ResourceManager.GetString("MSG_DUPLICATE_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A login with this email address does not exist!.
        /// </summary>
        public static string MSG_EMAIL_DOES_NOT_EXIST_ON_THE_SYSTEM {
            get {
                return ResourceManager.GetString("MSG_EMAIL_DOES_NOT_EXIST_ON_THE_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address!.
        /// </summary>
        public static string MSG_EMAIL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_EMAIL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is required!.
        /// </summary>
        public static string MSG_EXCHANGE_URL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_EXCHANGE_URL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version is required!.
        /// </summary>
        public static string MSG_EXCHANGE_VERSION_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_EXCHANGE_VERSION_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load languages at the moment. Please, try refreshing the current page.
        /// </summary>
        public static string MSG_FAILED_TO_LOAD_LANGUAGES {
            get {
                return ResourceManager.GetString("MSG_FAILED_TO_LOAD_LANGUAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required!.
        /// </summary>
        public static string MSG_FIRST_NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_FIRST_NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change.
        /// </summary>
        public static string MSG_FORGOT_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("MSG_FORGOT_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string MSG_HELLO {
            get {
                return ResourceManager.GetString("MSG_HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no need to select a tenant with the role administrator.
        /// </summary>
        public static string MSG_IF_USER_IS_ADMIN_THEN_TENANT_MUST_NULL {
            get {
                return ResourceManager.GetString("MSG_IF_USER_IS_ADMIN_THEN_TENANT_MUST_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email!.
        /// </summary>
        public static string MSG_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("MSG_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id.
        /// </summary>
        public static string MSG_INVALID_ID {
            get {
                return ResourceManager.GetString("MSG_INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login!.
        /// </summary>
        public static string MSG_INVALID_LOGIN {
            get {
                return ResourceManager.GetString("MSG_INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role name!.
        /// </summary>
        public static string MSG_INVALID_ROLE_NAME {
            get {
                return ResourceManager.GetString("MSG_INVALID_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token!.
        /// </summary>
        public static string MSG_INVALID_TOKEN {
            get {
                return ResourceManager.GetString("MSG_INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name!.
        /// </summary>
        public static string MSG_INVALID_USER_NAME {
            get {
                return ResourceManager.GetString("MSG_INVALID_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required!.
        /// </summary>
        public static string MSG_LAST_NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_LAST_NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string MSG_LOADING {
            get {
                return ResourceManager.GetString("MSG_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in!.
        /// </summary>
        public static string MSG_LOGIN_ALREADY_ASSOCIATED {
            get {
                return ResourceManager.GetString("MSG_LOGIN_ALREADY_ASSOCIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login type is required!.
        /// </summary>
        public static string MSG_LOGIN_TYPE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_LOGIN_TYPE_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client name may not contain more than 255 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_AZURE_CLIENT_IS_255 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_AZURE_CLIENT_IS_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure client secret may not contain more than 255 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_AZURE_CLIENT_SECRET_IS_255 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_AZURE_CLIENT_SECRET_IS_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure tenant name may not contain more than 255 characters.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_AZURE_TENANT_IS_255 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_AZURE_TENANT_IS_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email may not contain more than 75 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_EMAIL_IS_75 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_EMAIL_IS_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL may not contain more than 255 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_EXCHANGE_URL_IS_255 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_EXCHANGE_URL_IS_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of First Name is 50!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_FIRST_NAME_IS_50 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_FIRST_NAME_IS_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of Last Name is 50!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_LAST_NAME_IS_50 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_LAST_NAME_IS_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered name may not contain more than 50 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_NAME_IS {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_NAME_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name may not contain more than 255 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_NAME_IS_255 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_NAME_IS_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password may not contain more than 50 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_SERVICE_PASSWORD_IS_50 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_SERVICE_PASSWORD_IS_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL may not contain more than 255 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_SERVICE_URL_IS_255 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_SERVICE_URL_IS_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username may not contain more than 255 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_SERVICE_USER_IS_255 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_SERVICE_USER_IS_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username may not contain more than 255 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_SERVICE_USER_IS_50 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_SERVICE_USER_IS_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password may not contain more than 50 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_SERVICE_USER_PASSWORD_IS_50 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_SERVICE_USER_PASSWORD_IS_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered username may not contain more than 50 characters!.
        /// </summary>
        public static string MSG_MAX_LENGTH_OF_USERNAME_IS_50 {
            get {
                return ResourceManager.GetString("MSG_MAX_LENGTH_OF_USERNAME_IS_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length of First Name is 3!.
        /// </summary>
        public static string MSG_MIN_LENGTH_OF_FIRST_NAME_IS_3 {
            get {
                return ResourceManager.GetString("MSG_MIN_LENGTH_OF_FIRST_NAME_IS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length of Last Name is 3!.
        /// </summary>
        public static string MSG_MIN_LENGTH_OF_LAST_NAME_IS_3 {
            get {
                return ResourceManager.GetString("MSG_MIN_LENGTH_OF_LAST_NAME_IS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered username may contain at least 6 characters!.
        /// </summary>
        public static string MSG_MINLENGTH_OF_USERNAME_IS_6 {
            get {
                return ResourceManager.GetString("MSG_MINLENGTH_OF_USERNAME_IS_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required!.
        /// </summary>
        public static string MSG_NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found!.
        /// </summary>
        public static string MSG_NO_RECORD_FOUND_WITH_ID {
            get {
                return ResourceManager.GetString("MSG_NO_RECORD_FOUND_WITH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found!.
        /// </summary>
        public static string MSG_NO_RECORD_FOUND_WITH_ID_ {
            get {
                return ResourceManager.GetString("MSG_NO_RECORD_FOUND_WITH_ID_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number should be between 1 and 99999!.
        /// </summary>
        public static string MSG_NUMBER_MUST_BETWEEN_1_AND_99999 {
            get {
                return ResourceManager.GetString("MSG_NUMBER_MUST_BETWEEN_1_AND_99999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered old password does not match!.
        /// </summary>
        public static string MSG_OLD_PASSWORD_NOT_MATCHED {
            get {
                return ResourceManager.GetString("MSG_OLD_PASSWORD_NOT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters and numbers are allowed!.
        /// </summary>
        public static string MSG_ONLY_LETTERS_AND_NUMBERS_ARE_ALLOWED {
            get {
                return ResourceManager.GetString("MSG_ONLY_LETTERS_AND_NUMBERS_ARE_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        public static string MSG_PASSWORD_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password should contain between 6 and 100 characters!.
        /// </summary>
        public static string MSG_PASSWORD_IS_REQUIRED_MIN_LENGHT_IS_6_MAX_LENGHT_IS_100 {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_IS_REQUIRED_MIN_LENGHT_IS_6_MAX_LENGHT_IS_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mismatch.
        /// </summary>
        public static string MSG_PASSWORD_MISMATCH {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should contain at least one digit!.
        /// </summary>
        public static string MSG_PASSWORD_REQUIRES_DIGIT {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_REQUIRES_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should contain at least one lowercase character!.
        /// </summary>
        public static string MSG_PASSWORD_REQUIRES_LOWER {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_REQUIRES_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should contain at least one special character!.
        /// </summary>
        public static string MSG_PASSWORD_REQUIRES_NON_ALPHANUMERIC {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_REQUIRES_NON_ALPHANUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password should contain more unique characters!.
        /// </summary>
        public static string MSG_PASSWORD_REQUIRES_UNIQUE_CHARS {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_REQUIRES_UNIQUE_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should contain at least one uppercase character!.
        /// </summary>
        public static string MSG_PASSWORD_REQUIRES_UPPER {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_REQUIRES_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too weak!.
        /// </summary>
        public static string MSG_PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is required!.
        /// </summary>
        public static string MSG_PAYTYPE_DISPLAY_NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_PAYTYPE_DISPLAY_NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The servicecode does not exist!.
        /// </summary>
        public static string MSG_PAYTYPE_DOESNT_EXIST {
            get {
                return ResourceManager.GetString("MSG_PAYTYPE_DOESNT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password!.
        /// </summary>
        public static string MSG_PLEASE_CHECK_YOUR_EMAIL_TO_RESET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_PLEASE_CHECK_YOUR_EMAIL_TO_RESET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the required data!.
        /// </summary>
        public static string MSG_PLEASE_FILL_IN_THE_REQUIRED_FIELDS {
            get {
                return ResourceManager.GetString("MSG_PLEASE_FILL_IN_THE_REQUIRED_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking.
        /// </summary>
        public static string MSG_PLEASE_RESET_YOUR_PASSWORD_BY {
            get {
                return ResourceManager.GetString("MSG_PLEASE_RESET_YOUR_PASSWORD_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this ever appears...call Hoa!.
        /// </summary>
        public static string MSG_RECOVERY_CODE_REDEMPTION_FAILED {
            get {
                return ResourceManager.GetString("MSG_RECOVERY_CODE_REDEMPTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler should be between 1 and 180!.
        /// </summary>
        public static string MSG_SCHEDULER_SHOULD_BE_BETWEEN_1_AND_180 {
            get {
                return ResourceManager.GetString("MSG_SCHEDULER_SHOULD_BE_BETWEEN_1_AND_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reset Password email sent successfully to {0}..
        /// </summary>
        public static string MSG_SEND_RESET_PASSWORD_MAIL_TO {
            get {
                return ResourceManager.GetString("MSG_SEND_RESET_PASSWORD_MAIL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password email has been sent..
        /// </summary>
        public static string MSG_SENDING_EMAIL_FOR_FORGOT_PASSWORD_CAN_TAKE_MORE_THAN_10_MINUTES {
            get {
                return ResourceManager.GetString("MSG_SENDING_EMAIL_FOR_FORGOT_PASSWORD_CAN_TAKE_MORE_THAN_10_MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending emails is not successful. Please contact to the administrator!.
        /// </summary>
        public static string MSG_SENDING_EMAILS_IS_NOT_SUCCESSFUL__PLEASE_CONTACT_TO_THE_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("MSG_SENDING_EMAILS_IS_NOT_SUCCESSFUL._PLEASE_CONTACT_TO_THE_ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending emails is not successful. Please contact to the administrator!.
        /// </summary>
        public static string MSG_SENDING_EMAILS_IS_NOT_SUCCESSFUL_PLEASE_CONTACT_TO_THE_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("MSG_SENDING_EMAILS_IS_NOT_SUCCESSFUL_PLEASE_CONTACT_TO_THE_ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service password is required!.
        /// </summary>
        public static string MSG_SERVICE_PASSWORD_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_SERVICE_PASSWORD_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service port is required!.
        /// </summary>
        public static string MSG_SERVICE_PORT_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_SERVICE_PORT_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service port range is from 1 to 99999.
        /// </summary>
        public static string MSG_SERVICE_PORT_RANGE_IS_FROM_1_TO_99999 {
            get {
                return ResourceManager.GetString("MSG_SERVICE_PORT_RANGE_IS_FROM_1_TO_99999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL is required!.
        /// </summary>
        public static string MSG_SERVICE_URL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_SERVICE_URL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Use SSL is required!.
        /// </summary>
        public static string MSG_SERVICE_USE_SSL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_SERVICE_USE_SSL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service user is required!.
        /// </summary>
        public static string MSG_SERVICE_USER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_SERVICE_USER_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service user password is required!.
        /// </summary>
        public static string MSG_SERVICE_USER_PASSWORD_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_SERVICE_USER_PASSWORD_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tenant does not exist!.
        /// </summary>
        public static string MSG_TENANT_DOESNT_EXIST {
            get {
                return ResourceManager.GetString("MSG_TENANT_DOESNT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tenant does not exist or has been deactivated!.
        /// </summary>
        public static string MSG_TENANT_NOT_EXIST_OR_DISABLED {
            get {
                return ResourceManager.GetString("MSG_TENANT_NOT_EXIST_OR_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email is not valid!.
        /// </summary>
        public static string MSG_THE_EMAIL_FIELD_IS_NOT_A_VALID_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("MSG_THE_EMAIL_FIELD_IS_NOT_A_VALID_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email already exists!.
        /// </summary>
        public static string MSG_THE_ENTERED_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("MSG_THE_ENTERED_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email does not exist!.
        /// </summary>
        public static string MSG_THE_ENTERED_EMAIL_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("MSG_THE_ENTERED_EMAIL_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered name already exists!.
        /// </summary>
        public static string MSG_THE_ENTERED_NAME_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("MSG_THE_ENTERED_NAME_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered tenant Number already exists.
        /// </summary>
        public static string MSG_THE_ENTERED_NUMBER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("MSG_THE_ENTERED_NUMBER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match!.
        /// </summary>
        public static string MSG_THE_NEW_PASSWORD_AND_CONFIRMATION_PASSWORD_DO_NOT_MATCH {
            get {
                return ResourceManager.GetString("MSG_THE_NEW_PASSWORD_AND_CONFIRMATION_PASSWORD_DO_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match!.
        /// </summary>
        public static string MSG_THE_PASSWORD_AND_CONFIRMATION_PASSWORD_DO_NOT_MATCH {
            get {
                return ResourceManager.GetString("MSG_THE_PASSWORD_AND_CONFIRMATION_PASSWORD_DO_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should contain both upper and lower case letters!.
        /// </summary>
        public static string MSG_THE_PASSWORD_MUST_HAVE_UPPER_AND_LOWER_CASE_LETTERS {
            get {
                return ResourceManager.GetString("MSG_THE_PASSWORD_MUST_HAVE_UPPER_AND_LOWER_CASE_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This servicecode already exists!.
        /// </summary>
        public static string MSG_THIS_PAYTYPE_CODE_IS_USED_FOR_ANOTHER_PAYTYPE {
            get {
                return ResourceManager.GetString("MSG_THIS_PAYTYPE_CODE_IS_USED_FOR_ANOTHER_PAYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tenant has been used!.
        /// </summary>
        public static string MSG_THIS_TENANT_HAS_BEEN_USED {
            get {
                return ResourceManager.GetString("MSG_THIS_TENANT_HAS_BEEN_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user does not exist or is deactivated..
        /// </summary>
        public static string MSG_THIS_USER_DOES_NOT_EXIST_OR_IS_DEACTIVATED {
            get {
                return ResourceManager.GetString("MSG_THIS_USER_DOES_NOT_EXIST_OR_IS_DEACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user data!.
        /// </summary>
        public static string MSG_UNABLE_TO_LOAD_USER {
            get {
                return ResourceManager.GetString("MSG_UNABLE_TO_LOAD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been created successfully!.
        /// </summary>
        public static string MSG_USER_ALREADY_HAS_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_USER_ALREADY_HAS_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s role has been established!.
        /// </summary>
        public static string MSG_USER_ALREADY_IN_ROLE {
            get {
                return ResourceManager.GetString("MSG_USER_ALREADY_IN_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required!.
        /// </summary>
        public static string MSG_USER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_USER_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user lockout is not enabled.
        /// </summary>
        public static string MSG_USER_LOCKOUT_NOT_ENABLED {
            get {
                return ResourceManager.GetString("MSG_USER_LOCKOUT_NOT_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to update data! 
        ///.
        /// </summary>
        public static string MSG_USER_NOT_IN_ROLE {
            get {
                return ResourceManager.GetString("MSG_USER_NOT_IN_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your role has been changed on other device. This session will automatically end in {0} seconds or click Logout to end it now..
        /// </summary>
        public static string MSG_USER_PERMISSION_MAY_HAS_CHANGED_ON_OTHER_DEVICE {
            get {
                return ResourceManager.GetString("MSG_USER_PERMISSION_MAY_HAS_CHANGED_ON_OTHER_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this tenant?.
        /// </summary>
        public static string MSG_YOU_WANT_TO_DELETE_THIS_RECORD_WITH {
            get {
                return ResourceManager.GetString("MSG_YOU_WANT_TO_DELETE_THIS_RECORD_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account doesn&apos;t have the access permission. Please contact administrator for more information.
        /// </summary>
        public static string MSG_YOUR_ACCOUNT_DOESNT_HAVE_PERMISSION_TO_ACCESS_PLEASE_CONTACT_ADMINISTRATOR_FOR_MORE_INFORMATION {
            get {
                return ResourceManager.GetString("MSG_YOUR_ACCOUNT_DOESNT_HAVE_PERMISSION_TO_ACCESS_PLEASE_CONTACT_ADMINISTRATOR_FO" +
                        "R_MORE_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed!.
        /// </summary>
        public static string MSG_YOUR_PASSWORD_HAS_BEEN_CHANGED {
            get {
                return ResourceManager.GetString("MSG_YOUR_PASSWORD_HAS_BEEN_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated..
        /// </summary>
        public static string MSG_YOUR_PROFILE_HAS_BEEN_UPDATED {
            get {
                return ResourceManager.GetString("MSG_YOUR_PROFILE_HAS_BEEN_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NEW_PASSWORD {
            get {
                return ResourceManager.GetString("NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data displayed.
        /// </summary>
        public static string NO_DATA_TO_DISPLAY {
            get {
                return ResourceManager.GetString("NO_DATA_TO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OLD_PASSWORD {
            get {
                return ResourceManager.GetString("OLD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviccode.
        /// </summary>
        public static string PAY_TYPE_SETTING {
            get {
                return ResourceManager.GetString("PAY_TYPE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviccode setting.
        /// </summary>
        public static string PAY_TYPE_SETTING_TITTLE {
            get {
                return ResourceManager.GetString("PAY_TYPE_SETTING_TITTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviccode added!.
        /// </summary>
        public static string PAYTYPE_HAS_BEEN_ADDED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("PAYTYPE_HAS_BEEN_ADDED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviccode deleted!.
        /// </summary>
        public static string PAYTYPE_HAS_BEEN_DELETED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("PAYTYPE_HAS_BEEN_DELETED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviccode updated!.
        /// </summary>
        public static string PAYTYPE_HAS_BEEN_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("PAYTYPE_HAS_BEEN_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string POPUP_BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("POPUP_BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string POPUP_BUTTON_SAVE {
            get {
                return ResourceManager.GetString("POPUP_BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string POPUP_BUTTON_TEST {
            get {
                return ResourceManager.GetString("POPUP_BUTTON_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string POPUP_CANCEL {
            get {
                return ResourceManager.GetString("POPUP_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password.
        /// </summary>
        public static string POPUP_TEXT_TYPE_PASSWORD {
            get {
                return ResourceManager.GetString("POPUP_TEXT_TYPE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string POPUP_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("POPUP_TITLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string PRIVATE {
            get {
                return ResourceManager.GetString("PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version.
        /// </summary>
        public static string PRODUCT_VERSION {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home.
        /// </summary>
        public static string RESET_PASSWORD_BACK_TO_HOME {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_BACK_TO_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string RESET_PASSWORD_BUTTON_RESET {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in..
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_MSG_CLICK_HERE_TO_LOG_IN {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_MSG_CLICK_HERE_TO_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_MSG_YOU_CAN {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_MSG_YOU_CAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_MSG_YOUR_PASSWORD_HAS_BEEN_RESET {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_MSG_YOUR_PASSWORD_HAS_BEEN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_TITLE_RESET_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_TITLE_RESET_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string RESET_PASSWORD_MSG_RESET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_MSG_RESET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reset code is not valid..
        /// </summary>
        public static string RESET_PASSWORD_THE_RESET_CODE_IS_NOT_VALID {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_THE_RESET_CODE_IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string RESET_PASSWORD_TITLE_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_TITLE_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to back to the Login form.
        /// </summary>
        public static string RESET_PASSWORD_TO_BACK_TO_THE_LOGIN_FORM {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_TO_BACK_TO_THE_LOGIN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can click a link.
        /// </summary>
        public static string RESET_PASSWORD_YOU_CAN_CLICK_A_LINK {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_YOU_CAN_CLICK_A_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string ROLE {
            get {
                return ResourceManager.GetString("ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string SELECTED {
            get {
                return ResourceManager.GetString("SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service user.
        /// </summary>
        public static string SERVICE_USER {
            get {
                return ResourceManager.GetString("SERVICE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service password.
        /// </summary>
        public static string SERVICE_USER_PASSWORD {
            get {
                return ResourceManager.GetString("SERVICE_USER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SETTING {
            get {
                return ResourceManager.GetString("SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string STATE {
            get {
                return ResourceManager.GetString("STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string TENANT {
            get {
                return ResourceManager.GetString("TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TENANT_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("TENANT_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TENANT_BUTTON_DELETE {
            get {
                return ResourceManager.GetString("TENANT_BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TENANT_BUTTON_SAVE {
            get {
                return ResourceManager.GetString("TENANT_BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TENANT_DESCRIPTION {
            get {
                return ResourceManager.GetString("TENANT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TENANT_INFOMATION {
            get {
                return ResourceManager.GetString("TENANT_INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TENANT_NAME {
            get {
                return ResourceManager.GetString("TENANT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string TENANT_NO {
            get {
                return ResourceManager.GetString("TENANT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string TENANT_NUMBER {
            get {
                return ResourceManager.GetString("TENANT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abacus.
        /// </summary>
        public static string TENANT_SETTING_ABACUS_SETTING_NAME {
            get {
                return ResourceManager.GetString("TENANT_SETTING_ABACUS_SETTING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string TENANT_SETTING_EXCHANGE_SETTING {
            get {
                return ResourceManager.GetString("TENANT_SETTING_EXCHANGE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string TENANT_SETTING_MANAGE {
            get {
                return ResourceManager.GetString("TENANT_SETTING_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicecode.
        /// </summary>
        public static string TENANT_SETTING_PAY_TYPE_SETTING {
            get {
                return ResourceManager.GetString("TENANT_SETTING_PAY_TYPE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string TENANT_SETTING_SHEDULE_TIMER {
            get {
                return ResourceManager.GetString("TENANT_SETTING_SHEDULE_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TENANT_SETTINGS {
            get {
                return ResourceManager.GetString("TENANT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string TENANT_STATUS {
            get {
                return ResourceManager.GetString("TENANT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string TENANT_USER {
            get {
                return ResourceManager.GetString("TENANT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string TEST_CONNECTION {
            get {
                return ResourceManager.GetString("TEST_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test failed!.
        /// </summary>
        public static string TEST_FAIL {
            get {
                return ResourceManager.GetString("TEST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass!.
        /// </summary>
        public static string TEST_PASS {
            get {
                return ResourceManager.GetString("TEST_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string TITLE_LOG_IN {
            get {
                return ResourceManager.GetString("TITLE_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string UPDATE_PASSWORD {
            get {
                return ResourceManager.GetString("UPDATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string USER_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("USER_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string USER_BUTTON_CREATE {
            get {
                return ResourceManager.GetString("USER_BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string USER_BUTTON_DELETE {
            get {
                return ResourceManager.GetString("USER_BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string USER_BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("USER_BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string USER_COMMENT {
            get {
                return ResourceManager.GetString("USER_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string USER_EMAIL {
            get {
                return ResourceManager.GetString("USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string USER_FIRST_NAME {
            get {
                return ResourceManager.GetString("USER_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string USER_FULL_NAME {
            get {
                return ResourceManager.GetString("USER_FULL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string USER_LANGUAGE {
            get {
                return ResourceManager.GetString("USER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string USER_LAST_NAME {
            get {
                return ResourceManager.GetString("USER_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string USER_ROLE {
            get {
                return ResourceManager.GetString("USER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string USER_SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("USER_SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select role.
        /// </summary>
        public static string USER_SELECT_ROLE {
            get {
                return ResourceManager.GetString("USER_SELECT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tenant.
        /// </summary>
        public static string USER_SELECT_TENANT {
            get {
                return ResourceManager.GetString("USER_SELECT_TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string USER_STATUS {
            get {
                return ResourceManager.GetString("USER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string USER_TENANT {
            get {
                return ResourceManager.GetString("USER_TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string USER_USERNAME {
            get {
                return ResourceManager.GetString("USER_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!!.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
    }
}
